proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=audio_cache:10m max_size=500m inactive=12h use_temp_path=off;

server {
    listen 80;
    server_name _; # Символ подчеркивания означает "принимать запросы с любого IP или домена"
    client_max_body_size 50M;
    root /usr/share/nginx/html;
    index index.html;

    # ==== Раздача фронтенда ====
    location / {
        try_files $uri $uri/ /index.html;
    }

    # ==== API (для /task/*) ====
    location /task/ {
        proxy_pass http://backend:8000/task/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    # ==== Другие API пути ====
    location /lecture/ {
        proxy_pass http://backend:8000/lecture/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ==== WebSocket для task ====
    location /task/ws {
        proxy_pass http://backend:8000/task/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    location ~ ^/lectures/.*\.(ogg|mp3|wav|m4a|webm|flac)$ {
        proxy_pass http://storage:9000;
        proxy_set_header Host storage:9000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_force_ranges on;

        proxy_cache_methods GET;
        proxy_cache audio_cache;
        proxy_cache_key "$uri";
        proxy_cache_valid 200 12h;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;
    }

    # ==== Проксируем авторизацию ====
    location /auth/ {
        proxy_pass http://backend:8000/auth/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ==== Проксируем пользователя ====
    location /user/ {
        proxy_pass http://backend:8000/user/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ==== Кеш ассетов ====
    location /assets {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
