"""add celery things

Revision ID: 504ebac31133
Revises: 70a9695ba8ec
Create Date: 2025-10-18 13:58:18.092886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504ebac31133'
down_revision: Union[str, Sequence[str], None] = '70a9695ba8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('status', sa.String(), nullable=True))
    op.add_column('lectures', sa.Column('task_id', sa.String(), nullable=True))
    op.add_column('lectures', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lectures', 'updated_at')
    op.drop_column('lectures', 'task_id')
    op.drop_column('lectures', 'status')
    # ### end Alembic commands ###
